name: consumer-credit-analysis
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pandas
  - numpy
  - matplotlib
  - ipykernel
  - seaborn
  - scikit-learn
  - pip
  - pyyaml
  - pip:
      - fredapi
